[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
streamlit = "^1.44.1"
opencv-python = "^4.11.0.86"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
